package models;

import javax.persistence.*;
import java.util.Date;
import enums.GroupMemberShipStatusEnum;

/**
 * GroupMembership – Entity representing the association of a User with a Group.
 * 
 * This entity captures details of a user's membership in a group,
 * including their role, membership status, and join date.
 */
@Entity
public class GroupMembership {

    /**
     * The unique identifier for the GroupMembership record.
     * Primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The User entity representing the member of the group.
     * Establishes a many-to-one relationship.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * The Group entity to which the user belongs.
     * Establishes a many-to-one relationship.
     */
    @ManyToOne
    @JoinColumn(name = "group_id")
    private Group group;

    /**
     * The role of the user within the group.
     * Example roles: 'admin', 'member'.
     */
    private String role;

    /**
     * The current status of the user's membership in the group.
     * Uses GroupMemberShipStatusEnum for standardized status values.
     */
    @Enumerated(EnumType.STRING)
    private GroupMemberShipStatusEnum status;

    /**
     * The date and time when the user joined the group.
     */
    @Temporal(TemporalType.TIMESTAMP)
    private Date joinedDate;

    // ======================
    // Getters and Setters
    // ======================

    /**
     * Gets the unique ID of the GroupMembership record.
     *
     * @return The membership ID.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique ID for the GroupMembership record.
     *
     * @param id The ID to set.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the User entity who is a member of the group.
     *
     * @return The User entity.
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the User entity for this membership.
     *
     * @param user The User to assign.
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Gets the Group entity associated with this membership.
     *
     * @return The Group entity.
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the Group entity for this membership.
     *
     * @param group The Group to assign.
     */
    public void setGroup(Group group) {
        this.group = group;
    }

    /**
     * Gets the role of the user within the group.
     *
     * @return The role string.
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the role of the user within the group.
     *
     * @param role The role to assign.
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * Gets the current status of the membership.
     *
     * @return The membership status.
     */
    public GroupMemberShipStatusEnum getStatus() {
        return status;
    }

    /**
     * Sets the current status of the membership.
     *
     * @param status The status to assign.
     */
    public void setStatus(GroupMemberShipStatusEnum status) {
        this.status = status;
    }

    /**
     * Gets the date when the user joined the group.
     *
     * @return The joined date.
     */
    public Date getJoinedDate() {
        return joinedDate;
    }

    /**
     * Sets the date when the user joined the group.
     *
     * @param joinedDate The join date to assign.
     */
    public void setJoinedDate(Date joinedDate) {
        this.joinedDate = joinedDate;
    }
}
